version: '3.8'

services:
  postgres-app:
    image: postgres:16-alpine
    container_name: liveimprove-postgres
    environment:
      POSTGRES_DB: liveimprove
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-apppass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-app:/var/lib/postgresql/data
    networks:
      - liveimprove-net

#  redis:
#    image: redis:7-alpine
#    container_name: liveimprove-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - liveimprove-net

networks:
  liveimprove-net:
    driver: bridge

volumes:
  pgdata-app:
  pgdata-keycloak: